name = "otaserver"
main = "src/index.ts"
compatibility_date = "2023-05-18"

account_id = "9add4187b89e0aac0e5a951c893549dd"
workers_dev = true

[[r2_buckets]]
binding = 'r2' # <~ valid JavaScript variable name
bucket_name = 'ota-firmware'
